/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class minimardi_Piece */

#ifndef _Included_minimardi_Piece
#define _Included_minimardi_Piece
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     minimardi_Piece
 * Method:    valid_piece
 * Signature: (C)Z
 */
JNIEXPORT jboolean JNICALL Java_minimardi_Piece_valid_1piece
  (JNIEnv *, jclass, jchar);

/*
 * Class:     minimardi_Piece
 * Method:    valid_piece_not_empty
 * Signature: (C)Z
 */
JNIEXPORT jboolean JNICALL Java_minimardi_Piece_valid_1piece_1not_1empty
  (JNIEnv *, jclass, jchar);

/*
 * Class:     minimardi_Piece
 * Method:    makeSameColor
 * Signature: (CC)C
 */
JNIEXPORT jchar JNICALL Java_minimardi_Piece_makeSameColor
  (JNIEnv *, jclass, jchar, jchar);

#ifdef __cplusplus
}
#endif
#endif
