/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class minimardi_Utils */

#ifndef _Included_minimardi_Utils
#define _Included_minimardi_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     minimardi_Utils
 * Method:    setTimeControl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_minimardi_Utils_setTimeControl
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     minimardi_Utils
 * Method:    setCompTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_minimardi_Utils_setCompTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     minimardi_Utils
 * Method:    setOppTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_minimardi_Utils_setOppTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     minimardi_Utils
 * Method:    outOfTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_minimardi_Utils_outOfTime
  (JNIEnv *, jclass);

/*
 * Class:     minimardi_Utils
 * Method:    allocateTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_minimardi_Utils_allocateTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
