/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class minimardi_Board */

#ifndef _Included_minimardi_Board
#define _Included_minimardi_Board
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     minimardi_Board
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_minimardi_Board_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     minimardi_Board
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_minimardi_Board_nativeFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     minimardi_Board
 * Method:    emptyBoardNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_minimardi_Board_emptyBoardNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     minimardi_Board
 * Method:    printBoardNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_minimardi_Board_printBoardNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     minimardi_Board
 * Method:    chessBoardNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_minimardi_Board_chessBoardNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     minimardi_Board
 * Method:    onBoard
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_minimardi_Board_onBoard
  (JNIEnv *, jclass, jint);

/*
 * Class:     minimardi_Board
 * Method:    getPieceNative
 * Signature: (JI)C
 */
JNIEXPORT jchar JNICALL Java_minimardi_Board_getPieceNative
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     minimardi_Board
 * Method:    setPieceNative
 * Signature: (CIJ)V
 */
JNIEXPORT void JNICALL Java_minimardi_Board_setPieceNative
  (JNIEnv *, jclass, jchar, jint, jlong);

/*
 * Class:     minimardi_Board
 * Method:    rank
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_minimardi_Board_rank
  (JNIEnv *, jclass, jint);

/*
 * Class:     minimardi_Board
 * Method:    file
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_minimardi_Board_file
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
