/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class minimardi_Search */

#ifndef _Included_minimardi_Search
#define _Included_minimardi_Search
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     minimardi_Search
 * Method:    bestMove
 * Signature: (Lminimardi/Position;II)I
 */
JNIEXPORT jint JNICALL Java_minimardi_Search_bestMove
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     minimardi_Search
 * Method:    perft
 * Signature: (Lminimardi/Position;I)I
 */
JNIEXPORT jint JNICALL Java_minimardi_Search_perft
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
