/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class minimardi_MoveListStack */

#ifndef _Included_minimardi_MoveListStack
#define _Included_minimardi_MoveListStack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     minimardi_MoveListStack
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_minimardi_MoveListStack_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     minimardi_MoveListStack
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_minimardi_MoveListStack_nativeFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     minimardi_MoveListStack
 * Method:    newHistMovesNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_minimardi_MoveListStack_newHistMovesNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     minimardi_MoveListStack
 * Method:    pushNative
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_minimardi_MoveListStack_pushNative
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     minimardi_MoveListStack
 * Method:    popNative
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_minimardi_MoveListStack_popNative
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     minimardi_MoveListStack
 * Method:    lookNative
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_minimardi_MoveListStack_lookNative
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     minimardi_MoveListStack
 * Method:    lookAtHistNative
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_minimardi_MoveListStack_lookAtHistNative
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     minimardi_MoveListStack
 * Method:    initMoveListNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_minimardi_MoveListStack_initMoveListNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     minimardi_MoveListStack
 * Method:    pushHistNative
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_minimardi_MoveListStack_pushHistNative
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     minimardi_MoveListStack
 * Method:    popHistNative
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_minimardi_MoveListStack_popHistNative
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     minimardi_MoveListStack
 * Method:    lookHistNative
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_minimardi_MoveListStack_lookHistNative
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     minimardi_MoveListStack
 * Method:    freeMoveListNative
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_minimardi_MoveListStack_freeMoveListNative
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     minimardi_MoveListStack
 * Method:    sortMoveScoresNative
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_minimardi_MoveListStack_sortMoveScoresNative
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     minimardi_MoveListStack
 * Method:    lookStackNative
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_minimardi_MoveListStack_lookStackNative
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
